/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {
        //Create new rental agency
        RentalAgency agency = new RentalAgency();

        // Add vehicles to rental agency
        agency.addVehicle(new Car("C1", "Toyota Camry", 60.0, true));
        agency.addVehicle(new Car("C2", "Ford Focus", 45.0, false));
        agency.addVehicle(new Motocycle("m1", "Honda Gold Wing", 40));
        agency.addVehicle(new Truck("t1", "Toyota Tundra", 90));

        // View vehicles that are available under rental agency
        agency.viewVehicles();

        // Rent a vehicle to customers
        Customer customer1 = new Customer("Nureat", 27);
        Customer customer2 = new Customer("Sey" , 87);
        Customer customer3 = new Customer("Ahmed" , 32);

        //customer instances
        agency.rentVehicle("C1", customer1, 4);
        agency.rentVehicle("m1", customer2, 3);
        agency.rentVehicle("t1", customer3, 2);



        // View transactions after rentals
        agency.viewTransactions();

        // Return a rented vehicle
        agency.returnVehicle("TX-1");

        // View transactions again when car is returned
        agency.viewTransactions();
    }
}
